### ISSUE TITLE
Arguments alignment rule could be better or not used in its current form

### ISSUE THREAD

**Issue by MSzweda** [netguru/hound#8]
![jakitoalignkurrrr](https://cloud.githubusercontent.com/assets/1605904/6124104/bf216806-b10a-11e4-8daf-f2024cece817.jpg)

^
breaking long line in this manner should be legit
It doesn't look bad (ok, could be subjective, but look at it!), it doesn't detract from the code written or its presentation. Could we drop this rule or modify it to accept multiple arguments after break like this?

Thoughts? :(

Or just set it to always be indented with two spaces.

**Comment by nekath** [comment]
:-1:

**Comment by naliwajek** [comment]
:+1:

**Comment by marcindobry** [comment]
:-1:

**Comment by madsheep** [comment]
:+1: for 2 spaces indent

**Comment by marysieek** [comment]
:+1:

**Comment by sufleR** [comment]
:+1:

**Comment by bartoszkopinski** [comment]
:-1:  = 
```ruby
attributes :state, :provider_key, :is_multiple, 
  :completed_or_cancelled_at
```
:+1:  = 
```ruby
attributes :state, :provider_key, :is_multiple, 
           :completed_or_cancelled_at
```
